# Generated by Django 4.2.2 on 2023-06-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='posts/pictures', verbose_name='picture'),
        ),
    ]
